// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ice tag",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "ice tag",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Required for Voice Chat."),
                .speechRecognition(purposeString: "Required for voice chat to work with voice moderation."),
                .appTransportSecurity(configuration: .init(
                    exceptionDomains: [
                        .init(
                            domainName: "https://sites.google.com/view/icelabs",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://sites.google.com/view/icelabs/mods",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://sites.google.com/view/icelabs/terms-of-service",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://sites.google.com/view/icelabs/privacy-policy",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://sites.google.com/view/icelabs/ice-tag-system-requirements",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://forms.gle/aWVrD8SiwuLpYHUr8",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://docs.google.com/forms/d/e/1FAIpQLSdpmSMI_wcW9uCziT6FIaIBe6ylMqj9aQwOwjAQ42dij7T4Sw/viewform",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://jackww51.itch.io/iceygame",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://grabvr.quest/levels/viewer/?level=2dahfrbinl80vn8h8u754:1725132872",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        )
                    ]
                )),
                .outgoingNetworkConnections()
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
